name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - windows-11-arm
          - macos-13
          - macos-15
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@main
        with:
          aqua_version: v2.53.4
          policy_allow: "true"
      - run: |
          command=$(cat aqua.yaml | grep '^\s*# TEST:' | sed 's/^\s*# TEST: //')
          if [ -z "$command" ]; then
            echo "No command to test found in aqua.yaml"
            exit 1
          fi
          echo "command=$command" >> "$GITHUB_OUTPUT"
        id: get-command
      - run: ${{ steps.get-command.outputs.command }}
