name: autofix.ci

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - windows-11-arm
          - macos-13
          - macos-15
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: aquaproj/aqua-installer
        with:
          aqua_version: v2.53.4
      - run: |
          command=$(cat aqua.yaml | grep '^\\s*# TEST:' | sed 's/^\\s*# TEST: //')
          echo "command=$command" >> "$GITHUB_OUTPUT"
        id: get-command
      - run: ${{ steps.get-command.outputs.command }}
