name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.get-command.outputs.command }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract command from aqua.yaml
        id: get-command
        run: |
          command=$(cat aqua.yaml | grep '^\s*# TEST:' | sed 's/^\s*# TEST: //')
          if [ -z "$command" ]; then
            echo "No command to test found in aqua.yaml"
            exit 1
          fi
          echo "command=$command" >> "$GITHUB_OUTPUT"

  test:
    needs: extract
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - windows-11-arm
          - macos-13
          - macos-15
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      AQUA_DISABLE_POLICY: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@main
        with:
          aqua_version: v2.53.4
          aqua_opts: ""
      - run: ${{ needs.extract.outputs.command }}
